baseURL = 'https://papunmohanty.github.io/builderlog/'
locale = 'en-us'
title = 'My New Hugo Project'
[params]
    maxAllowedWidth = "max-w-6xl"
    logo = "assets/my_profile_pic.jpeg"
[caches]
    [caches.images]
        dir = ':cacheDir/images'